### ISSUE TITLE
Audio Passthrough Sync issue

### ISSUE THREAD

**Issue by MilhouseVH** [FernetMenta/xbmc#339]
Discussing this with @fritsch on #irc, he suggested I open an issue.

Hardware: Revo 3700 with ION2, Onkyo TX-NR828 AVR
Software: OpenELEC Nvidia_Legacy build [#1205](http://forum.kodi.tv/showthread.php?tid=238393&pid=2179316#pid2179316) based on [PR8486](https://github.com/xbmc/xbmc/pull/8486)

Issue:

With recent builds when passthrough audio is enabled, audio sync is significantly off (delayed/behind video) - maybe by up to a second or two. It's like this from the very beginning of playback, and seems to affect most (if not all videos).

If I disable passthrough, audio sync is no longer an issue.

If I disable "Adjust display refresh rate" (and enable passthrough), there is no audio sync issue.

This is a debug log from build [#1205](http://forum.kodi.tv/showthread.php?tid=238393&pid=2179316#pid2179316) (passthrough enabled; addjust display refresh rate "Always"), playing 3 videos, all with significant up to 2-second audio sync issues: http://sprunge.us/PYQE

These are my settings:

![s1](http://i.imgur.com/NQX6BAw.png)
![s2](http://i.imgur.com/Yr52AU4.png)
![s3](http://i.imgur.com/OmdEa9b.png)
![s4](http://i.imgur.com/FJrLFCI.png)
![s5](http://i.imgur.com/EBWu5mW.png)

I don't have passthrough audio sync issues with build [#1121](http://forum.kodi.tv/showthread.php?tid=238393&pid=2167501#pid2167501), the audio sync issues start with build [#1125](http://forum.kodi.tv/showthread.php?tid=238393&pid=2170381#pid2170381).

Build [#1121](http://forum.kodi.tv/showthread.php?tid=238393&pid=2167501#pid2167501) debug log (passthrough enabled; adjust display refresh rate "always"): http://sprunge.us/JdSU (Arrow in sync., Saving Hope in sync, Paper Towns in sync)

Build [#1125](http://forum.kodi.tv/showthread.php?tid=238393&pid=2170381#pid2170381) debug log (passthrough enabled; adjust display refresh rate "always"): http://sprunge.us/XShC (Arrow out of sync, Saving Hope out of sync, curiously Paper Towns - resumed at about 11 minutes - is in sync)

If I set "Adjust display refresh rate" to "Off" then all builds, including [#1125](http://forum.kodi.tv/showthread.php?tid=238393&pid=2170381#pid2170381) and [#1205](http://forum.kodi.tv/showthread.php?tid=238393&pid=2179316#pid2179316), have no passthrough audio issues - all passthrough audio is now in sync.

Build [#1205](http://forum.kodi.tv/showthread.php?tid=238393&pid=2179316#pid2179316) debug log (passthrouigh enabled; adjust refresh rate set to "Off"): http://sprunge.us/BZZZ

**Comment by FernetMenta** [comment]
fixed on videoplayer branch

**Comment by fritsch** [comment]
@FernetMenta could you point to the commit that fixed it? I am curious as I read the code before and I'd like to know - as it seems to be squashed.

**Comment by MilhouseVH** [comment]
Passthrough audio with the latest PR8486 is now working really well, many thanks. Closing this issue as fixed.

However there is an issue with DTS HDMA and TrueHD, I'll open a separate issue for that.

**Comment by FernetMenta** [comment]
@fritsch it always comes down to the same mistake devs do: mistakes in doing abstractions and trying to implement things for the future that never happen. In this case the code was prepared that audio decoder can set pts. If pts is not set, audio player will set it. The point is that we have only 2 decoders: ffmpeg and passthrough and neither set pts:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.cpp#L132

one of the things amongst a trillion that needs correction but this is work for another day.

**Comment by MilhouseVH** [comment]
Just testing [a new build](http://forum.kodi.tv/showthread.php?tid=238393&pid=2181572#pid2181572) and the passthrough audio sync issue is back - did it not make it into xbmc/master?

This is the debug log: http://sprunge.us/OegD

Reopening as it doesn't appear to have been fixed (at least, not yet in xbmc/master).

**Comment by FernetMenta** [comment]
The fix is in mainline master. Can you reproduce with my master? Works here.

**Comment by MilhouseVH** [comment]
I've re-tested the build I said was working on 6 December, and that is still working fine.

A build of xbmc/master is not working - this has passthrough audio sync issues.

I also tried a build of xbmc/master with the delta comparison from your branch (ie. [these extra commits](https://github.com/xbmc/xbmc/compare/xbmc:a18e22d1c8e83f21e72daad0c414584a64363d55...FernetMenta:7a7752ef26a9e7e0f85a1b058f196daf0da229f0) on top, and that too is not working - the same passthrough audio sync issue.

I will now try an OE build based solely on your FernemtMenta/master branch (repackaged etc. for OpenELEC).

**Comment by fritsch** [comment]
That's why I asked here: https://github.com/FernetMenta/xbmc/issues/339#issuecomment-162349046 I also could not find the diff that should have made it work.

**Comment by MilhouseVH** [comment]
This is the debug log from an OpenELEC build (Nvidia_Legacy) based on FernetMenta/master: http://sprunge.us/WHRQ

This has the same passthrough audio problems originally reported here, that were fixed in xbmc/master on 6 December. Perhaps a subsequent commit has "undone" what was working on 6 December? I'll see if I can confirm that.

**Comment by FernetMenta** [comment]
I can't reproduce the issue with my master

**Comment by MilhouseVH** [comment]
I've just build OE + FernetMenta/master with HEAD=32af4975182bdb9e07559862731810067c020bf0, and that's working fine - no problems with passthrough audio. So the problem appears afterwards... oh joy.

**Comment by MilhouseVH** [comment]
I can reproduce the sync problem with these commits: https://github.com/FernetMenta/xbmc/commits/547e2c914a04612646f694c08f2998709defeefe

6cd277c087e5e56bac254ba76ad670ffa043365e is GOOD (passthrough audio is in sync, but TrueHD/DTSHD stutter and AC3 seek crashes)
547e2c914a04612646f694c08f2998709defeefe is BAD (passthrough audio is not in sync, however AC3 seek does NOT crash etc.)

So the fix for [TruedHD/DTS HD stutter](https://github.com/FernetMenta/xbmc/issues/340#issuecomment-162440130) (and which also fixed AC3 crashes when seeking) appears to have broken passthrough audio sync. Does this make sense? I've tested these two builds several times now and adding 547e2c914a always results in the passthrough audio sync problem.

I've also now rebuilt xbmc/master with and without #8512 (aka 547e2c914a): without #8512 and passthrough audio sync is working as expected (but TrueHD/DTSHD now stutters, and AC3 seek crashes). With #8512 and passthrough audio is always out of sync, while the other issues are fixed.

**Comment by FernetMenta** [comment]
this should do:
https://github.com/FernetMenta/xbmc/commit/e5850fa8696e43308042cd0f1046eda1f6d23439

**Comment by MilhouseVH** [comment]
Hi many thanks - I've given it a quick test (sorry, bit pushed for time today - tested 5 problem videos) and all three issues appear to be fixed by https://github.com/FernetMenta/xbmc/commit/e5850fa8696e43308042cd0f1046eda1f6d23439:

1. Passthrough audio sync - FIXED
2. TrueHD/DTS HD stutter - FIXED
3. Seek crash - FIXED
